SELECT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
WHERE c.CAR_TYPE = '세단'
AND EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    WHERE c.CAR_ID = h.CAR_ID
    AND MONTH(h.START_DATE) = 10
)
ORDER BY CAR_ID DESC;