SELECT I1.ITEM_ID
     , I1.ITEM_NAME
     , I1.RARITY
FROM (
     SELECT I.ITEM_ID
          , I.ITEM_NAME
          , I.RARITY
          , T.PARENT_ITEM_ID
     FROM ITEM_INFO I
     JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
 ) I1
WHERE EXISTS (
    SELECT 1
    FROM ITEM_INFO I2
    WHERE I1.PARENT_ITEM_ID = I2.ITEM_ID
    AND I2.RARITY = 'RARE'
)
ORDER BY I1.ITEM_ID DESC;