WITH Temptable AS (
    SELECT PARENT_ID AS ID
         , COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT e1.ID AS ID
     , IFNULL(t.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e1
LEFT JOIN Temptable t ON e1.ID = t.ID
