SELECT i1.ANIMAL_ID
     , i1.NAME
FROM ANIMAL_INS i1
WHERE EXISTS (
    SELECT 1
    FROM ANIMAL_INS i2
    WHERE i1.ANIMAL_ID = i2.ANIMAL_ID
    AND ANIMAL_TYPE = 'Dog'
    AND i2.NAME LIKE '%el%'
)
ORDER BY NAME;