WITH RECURSIVE CTE AS (
    SELECT 1 AS GENERATION
         , ID
         , PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT GENERATION + 1
         , E.ID
         , C.ID
    FROM CTE C
    JOIN ECOLI_DATA E ON C.ID = E.PARENT_ID
)
SELECT COUNT(*) AS COUNT
     , GENERATION
FROM CTE C1
WHERE NOT EXISTS (
    SELECT 1
    FROM CTE C2
    WHERE C1.ID = C2.PARENT_ID
)
GROUP BY GENERATION
ORDER BY GENERATION;