SELECT U.USER_ID
     , U.NICKNAME
     , B.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT WRITER_ID
         , SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
) B ON U.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_SALES;