WITH TEMP AS (
    SELECT USER_ID
         , PRODUCT_ID
         , SALES_AMOUNT
         , SALES_DATE
    FROM ONLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'
    UNION ALL
    SELECT NULL
         , PRODUCT_ID
         , SALES_AMOUNT
         , SALES_DATE
    FROM OFFLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'
)
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM TEMP
GROUP BY SALES_DATE, PRODUCT_ID, USER_ID
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;