SELECT t2.YEAR
     , t2.SIZE_OF_COLONY - t1.SIZE_OF_COLONY AS YEAR_DEV
     , t1.ID
FROM ECOLI_DATA t1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
         , MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR
) t2 ON YEAR(t1.DIFFERENTIATION_DATE) = t2.YEAR
ORDER BY t2.YEAR, YEAR_DEV;


SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
     , (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE) ORDER BY SIZE_OF_COLONY DESC) - SIZE_OF_COLONY) AS YEAR_DEV
     , ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;