WITH RECURSIVE CTE AS (
    SELECT 0 AS I
    UNION ALL
    SELECT I + 1
    FROM CTE
    WHERE I < 23
)
SELECT C.I AS HOUR
     , IFNULL(A.COUNT, 0) AS COUNT
FROM CTE C
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR
         , COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) AS A ON C.I = A.HOUR
ORDER BY C.I;