SELECT i.ANIMAL_ID
     , i.ANIMAL_TYPE
     , i.NAME
FROM ANIMAL_INS i
WHERE EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS o
    WHERE i.ANIMAL_ID = o.ANIMAL_ID
      AND o.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
)
AND i.SEX_UPON_INTAKE LIKE 'Intact%';