SELECT T1.CAR_ID
     , IF(T2.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) T1 LEFT JOIN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16'
    AND END_DATE >= '2022-10-16'
) T2 ON T1.CAR_ID = T2.CAR_ID
ORDER BY T1.CAR_ID DESC;