SELECT COUNT(*) AS FISH_COUNT
     , MAX(LENGTH) AS MAX_LENGTH
     , FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IF(LENGTH < 10 OR LENGTH IS NULL, 10, LENGTH)) >= 33
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;