WITH TEMP AS (
    SELECT ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
         , PRICE AS MAX_PRICE
         , CATEGORY
         , PRODUCT_NAME
    FROM FOOD_PRODUCT
)
SELECT CATEGORY
     , MAX_PRICE
     , PRODUCT_NAME
FROM TEMP
WHERE RN = 1
AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;